# Generated by Django 3.2.2 on 2021-06-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210614_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_discription',
            field=models.CharField(default='Описания категории', max_length=64),
        ),
    ]
