# Generated by Django 3.2.2 on 2021-06-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_category_category_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_discription',
            field=models.CharField(default='', max_length=64),
        ),
    ]
