# Generated by Django 3.2.2 on 2021-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_category_category_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_discription',
            field=models.TextField(default=''),
        ),
    ]
