# Generated by Django 3.2.2 on 2021-06-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20210616_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='-', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='positions',
            field=models.CharField(choices=[('PA', 'Статья'), ('PN', 'Новость')], default='PA', max_length=2, verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='news.PostCategory', to='news.Category', verbose_name='Категория поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='previewName',
            field=models.CharField(max_length=128, verbose_name='Превью поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
