# Generated by Django 3.2.2 on 2021-06-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20210616_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='news.PostCategory', to='news.Category', verbose_name='Категория поста'),
        ),
    ]
