# Generated by Django 3.2.2 on 2021-06-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_post_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
