# Generated by Django 3.2.2 on 2021-06-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='photos/def/blur.jpg', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
