# Generated by Django 3.2.2 on 2021-07-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_remove_post_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
