# Generated by Django 3.2.2 on 2021-07-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_rename_commentpost_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='user',
        ),
    ]
