# Generated by Django 3.2.2 on 2021-07-11 14:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_rename_commentuser_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст поста'),
        ),
    ]
