# Generated by Django 3.2.2 on 2021-07-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_alter_post_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
