# Generated by Django 3.2.2 on 2021-07-15 17:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='news.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='news.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
